version: "3.1"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: security123
      POSTGRES_USER: securityuser
      POSTGRES_DB: securityservice
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db