server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.data.r2dbc: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.speech4j.securityservice: DEBUG
    org.speech4j.securityservice.service: DEBUG

spring:
  data:
    postgres:
      host: "db"
      port: 5432
      username: "securityuser"
      password: "security123"
      database: "securityservice"

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 398918112673-5vg9qr3677q3g1vlc0drga6edrshbp99.apps.googleusercontent.com
#            client-secret: jtvCtZnAcozeTU89hdilr6av
#            scope: openid, https://www.googleapis.com/auth/userinfo.email, https://www.googleapis.com/auth/userinfo.profile
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/auth
#            token-uri: https://www.googleapis.com/oauth2/v3/token
#            user-info-uri: https://www.googleapis.com/userinfo/v2/me
jwt:
  secret: "ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength"
  expiration: 100500
